### PR TITLE
Glimpse.ApplicationInsights

### PR DESCRIPTION
**Pull request by JoseCarlosMM**
Glimpse.ApplicationInsights and Glimpse.ApplicationInsights.Sample added. 
Unit test project created.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Try to use English in the commit names.

**Comment by SergeyKanzhelev** [comment]
Pull request is huge and it impossible to leave comments right in code. So I'll leave it here. Also next time please split it into multiple PRs.
1. In Sample.ApplicaitonInsights project you should replace refereces to the projects like: `<ProjectReference Include="..\Glimpse.Ado.Net45\Glimpse.Ado.Net45.csproj">` to the references on nugget packages. Those projects should not be moved to this repository.
2. What is `..\..\tools\WebApplicationsBuild\Microsoft.WebApplication.targets` for? DO we need it in this repository? Have you moved it here?
3. I see number of javascript files in PR like jquery and modernizr. DO they need to be checked in or they will be restored from NuGet? I don't know - thus the question
4. File `Glimpse.ApplicationInsights/ApplicationInsights.config` is not needed. Maybe it was added by mistake before. Can be removed.
5. All nupkg files should not be included into PR. Make sure you have .gitignore entry for this.
6. Same goes for dll and pdb files from the nupkg

**Comment by JoseCarlosMM** [comment]
Sorry for that, I have sent you another PR, this time only with the Glimpse.ApplicationInsights project and the issues solved for that project.

**Comment by SergeyKanzhelev** [comment]
I'll close this PR as it is outdated

**Pull request closed without merging**
